version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - redis
      - mailhog
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
